MessagesApp/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/messages' => 'messages#index'
  get '/messages/new' => 'messages#new'
  post '/messages'=> 'messages#create'
end

MessagesApp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

MessagesApp/app/models/message.rb
class Message < ApplicationRecord
end

MessagesApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

MessagesApp/app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    def index
        @messages = Message.all
    end
    def new
        @message = Message.new
    end
    def create
        @message = Message.new(message_params)
        if @message.save
            redirect_to "/messages"
        else
            render "new"
        end
    end
    private
    def message_params
        params.require(:message).permit(:content)
    end
end

MessagesApp/app/helpers/application_helper.rb
module ApplicationHelper
end

MessagesApp/app/helpers/messages_helper.rb
module MessagesHelper
end

MessagesApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessagesApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

MessagesApp/app/views/messages/index.html.erb
<div class="header">
  <div class="container">
    <img src="http://s3.amazonaws.com/codecademy-content/courses/learn-rails/img/logo-1m.svg" height="100" width="200">
    <h1>Messenger</h1>
  </div>
</div>

<div class="messages">
  <div class="container">
    <% @messages.each do |message| %>
            <div class="message">
            <p class="content"><%= message.content %></p>
            <p class="time"><%= message.created_at %></p>
            </div>
        <% end %>
        <a href="messages/new">New Message</a>
  </div>
</div>

MessagesApp/app/views/messages/new.html.erb
<%= form_for(@message,options = {as: :message, url: messages_path, method: :post}) do |f| %>
  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit "Create" %>
  </div>
<% end %>