MovieApp/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    get '/movies' => 'movies#index'
    get '/movies/:id' => 'movies#show', as: :movie
end

MovieApp/app/models/actor.rb
class Actor < ApplicationRecord
    has_many :parts
    has_many :movies, through: :parts
end

MovieApp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

MovieApp/app/models/movie.rb
class Movie < ApplicationRecord
    has_many :parts
    has_many :actors, through: :parts
end

MovieApp/app/models/part.rb
class Part < ApplicationRecord
    belongs_to :movie
    belongs_to :actor
end

MovieApp/app/controllers/actors_controller.rb
class ActorsController < ApplicationController
    def index
        @actors = Actor.all
    end

    def show
        @actor = Actor.find(params[:id])
        @movies = @actor.movies
    end
end

MovieApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

MovieApp/app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end

  def show
    @movie = Movie.find(params[:id])
    @actors = @movie.actors
  end
end

MovieApp/app/helpers/actors_helper.rb
module ActorsHelper
end

MovieApp/app/helpers/application_helper.rb
module ApplicationHelper
end

MovieApp/app/helpers/movies_helper.rb
module MoviesHelper
end

MovieApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

MovieApp/app/views/movies/index.html.erb
<div class="hero">
  <div class="container">
    <h2>Interstellar</h2>
    <p>Former NASA pilot Cooper (Matthew McConaughey) and a team of researchers travel across the galaxy to find out which of three planets could be mankind's new home.</p>
    <a href= "/movies/10">Read More</a>

  </div>
</div>

<div class="main">
  <div class="container">
  <h2>Popular Films</h2>
    <% @movies.each do |movie| %>
    <div class="movie">
      <%= image_tag movie.image %>
      <h3><%= movie.title %></h3>
      <p><%= movie.release_year %></p>
      <p><%= movie.plot %></p>
      <%= link_to "Learn more", movie_path(movie) %>
    </div>
    <% end %>
  </div>
</div>

MovieApp/app/views/movies/show.html.erb
<div class="main movie-show">
  <div class="container">
    <div class="movie">

      <!-- Display the movie's info here -->
      <div class="info">
        <!-- movie image -->
        <%= image_tag(@movie.image, :alt => "alternative text") %>
        <h3 class="movie-title"> <%=@movie.title%></h3>
        <p class="movie-release-year"><%=@movie.release_year%></p>
        <p class="movie-plot"><%=@movie.plot%></p>
      </div>
    </div>

    <h2>Cast</h2>
    <!-- Display each actor's info here -->
    <% @actors.each do |f| %>
    <div class="actor">
        <%= image_tag(f.image, :alt => "alternative text") %>
        <h3 class="actor-name"><%=f.first_name%> <%=f.last_name%></h3>
        <p class="actor-bio"><%=f.bio%></p>
    </div>
        <% end %>
  </div>
</div>